language: rust
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: stable
    - rust: beta
before_script: (cargo install rustfmt || true)
script:
  - export PATH="${PATH}:~/.cargo/bin"
  - cargo fmt -- --write-mode=diff
  - cargo test --verbose
  - cargo run --verbose --bin hello
  - cargo run --verbose --bin head -- -h
  - cargo run --verbose --bin head -- -n100 /var/log/dpkg.log
  - cargo run --verbose --bin tail -- -h
  - cargo run --verbose --bin tail -- -n100 /var/log/dpkg.log
  - cargo bench
after_success:
  - scripts/build_kcov.sh
  - scripts/send_kcov.sh
  - bash <(curl -s https://codecov.io/bash)
